# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: "commaneverends.github.io"
baseurl: "/"
url: "https://commaneverends.github.io"

header_pages:
  - index.md
  - a_music.md
  - a_literature.md
  - a_film.md
  - a_map.md
  - a_link.md
  - contact.md

footer: '© 2020 created with love by commaneverends. <br/> follow us on <a href="https://twitter.com/commaneverends">twitter</a> <a href="https://www.instagram.com/commaneverends/">instagram</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
