var markers = [
  {
    name: 'Schokofabrik',
    city: 'Mariannenstraße 6. 10997 Berlin',
    iata_faa: 'GKA',
    icao: 'AYGA',
    lat: 52.50090765,
    lng: 13.423274314933629,
    alt: 5282,
    tz: 'Networking',
  },
  {
    name: 'Madang2',
    city: 'Madang, Papua New Guinea',
    iata_faa: 'MAG',
    icao: 'AYGA',
    lat: 52.50090760,
    lng: 13.423274314933629,
    alt: 5282,
    tz: 'Networking',
  },
  {
    name: 'Mount Hagen',
    city: 'Mount Hagen, Papua New Guinea',
    iata_faa: 'HGU',
    icao: 'AYMH',
    lat: -5.826789,
    lng: 144.295861,
    alt: 5388,
    tz: 'Pacific/Port_Moresby',
  },
  {
    name: 'Nadzab',
    city: 'Nadzab, Papua New Guinea',
    iata_faa: 'LAE',
    icao: 'AYNZ',
    lat: -6.569828,
    lng: 146.726242,
    alt: 239,
    tz: 'Pacific/Port_Moresby',
  },
  {
    name: 'Port Moresby Jacksons Intl',
    city: 'Port Moresby, Papua New Guinea',
    iata_faa: 'POM',
    icao: 'AYPY',
    lat: -9.443383,
    lng: 147.22005,
    alt: 146,
    tz: 'Pacific/Port_Moresby',
  },
  {
    name: 'Wewak Intl',
    city: 'Wewak, Papua New Guinea',
    iata_faa: 'WWK',
    icao: 'AYWK',
    lat: -3.583828,
    lng: 143.669186,
    alt: 19,
    tz: 'Pacific/Port_Moresby',
  },
  {
    name: 'Narsarsuaq',
    city: 'Narssarssuaq, Greenland',
    iata_faa: 'UAK',
    icao: 'BGBW',
    lat: 61.160517,
    lng: -45.425978,
    alt: 112,
    tz: 'America/Godthab',
  },
  {
    name: 'Nuuk',
    city: 'Godthaab, Greenland',
    iata_faa: 'GOH',
    icao: 'BGGH',
    lat: 64.190922,
    lng: -51.678064,
    alt: 283,
    tz: 'America/Godthab',
  },
  {
    name: 'Sondre Stromfjord',
    city: 'Sondrestrom, Greenland',
    iata_faa: 'SFJ',
    icao: 'BGSF',
    lat: 67.016969,
    lng: -50.689325,
    alt: 165,
    tz: 'America/Godthab',
  },
  {
    name: 'Thule Air Base',
    city: 'Thule, Greenland',
    iata_faa: 'THU',
    icao: 'BGTL',
    lat: 76.531203,
    lng: -68.703161,
    alt: 251,
    tz: 'America/Thule',
  },
  {
    name: 'Akureyri',
    city: 'Akureyri, Iceland',
    iata_faa: 'AEY',
    icao: 'BIAR',
    lat: 65.659994,
    lng: -18.072703,
    alt: 6,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Egilsstadir',
    city: 'Egilsstadir, Iceland',
    iata_faa: 'EGS',
    icao: 'BIEG',
    lat: 65.283333,
    lng: -14.401389,
    alt: 76,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Hornafjordur',
    city: 'Hofn, Iceland',
    iata_faa: 'HFN',
    icao: 'BIHN',
    lat: 64.295556,
    lng: -15.227222,
    alt: 24,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Husavik',
    city: 'Husavik, Iceland',
    iata_faa: 'HZK',
    icao: 'BIHU',
    lat: 65.952328,
    lng: -17.425978,
    alt: 48,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Isafjordur',
    city: 'Isafjordur, Iceland',
    iata_faa: 'IFJ',
    icao: 'BIIS',
    lat: 66.058056,
    lng: -23.135278,
    alt: 8,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Keflavik International Airport',
    city: 'Keflavik, Iceland',
    iata_faa: 'KEF',
    icao: 'BIKF',
    lat: 63.985,
    lng: -22.605556,
    alt: 171,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Patreksfjordur',
    city: 'Patreksfjordur, Iceland',
    iata_faa: 'PFJ',
    icao: 'BIPA',
    lat: 65.555833,
    lng: -23.965,
    alt: 11,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Reykjavik',
    city: 'Reykjavik, Iceland',
    iata_faa: 'RKV',
    icao: 'BIRK',
    lat: 64.13,
    lng: -21.940556,
    alt: 48,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Siglufjordur',
    city: 'Siglufjordur, Iceland',
    iata_faa: 'SIJ',
    icao: 'BISI',
    lat: 66.133333,
    lng: -18.916667,
    alt: 10,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Vestmannaeyjar',
    city: 'Vestmannaeyjar, Iceland',
    iata_faa: 'VEY',
    icao: 'BIVM',
    lat: 63.424303,
    lng: -20.278875,
    alt: 326,
    tz: 'Atlantic/Reykjavik',
  },
  {
    name: 'Sault Ste Marie',
    city: 'Sault Sainte Marie, Canada',
    iata_faa: 'YAM',
    icao: 'CYAM',
    lat: 46.485001,
    lng: -84.509445,
    alt: 630,
    tz: 'America/Toronto',
  },
  {
    name: 'Winnipeg St Andrews',
    city: 'Winnipeg, Canada',
    iata_faa: 'YAV',
    icao: 'CYAV',
    lat: 50.056389,
    lng: -97.0325,
    alt: 760,
    tz: 'America/Winnipeg',
  },
  {
    name: 'Shearwater',
    city: 'Halifax, Canada',
    iata_faa: 'YAW',
    icao: 'CYAW',
    lat: 44.639721,
    lng: -63.499444,
    alt: 167,
    tz: 'America/Halifax',
  },
  {
    name: 'St Anthony',
    city: 'St. Anthony, Canada',
    iata_faa: 'YAY',
    icao: 'CYAY',
    lat: 51.391944,
    lng: -56.083056,
    alt: 108,
    tz: 'America/St_Johns',
  },
  {
    name: 'Tofino',
    city: 'Tofino, Canada',
    iata_faa: 'YAZ',
    icao: 'CYAZ',
    lat: 49.082222,
    lng: -125.7725,
    alt: 80,
    tz: 'America/Vancouver',
  },
  {
    name: 'Kugaaruk',
    city: 'Pelly Bay, Canada',
    iata_faa: 'YBB',
    icao: 'CYBB',
    lat: 68.534444,
    lng: -89.808056,
    alt: 56,
    tz: 'America/Edmonton',
  },
  {
    name: 'Baie Comeau',
    city: 'Baie Comeau, Canada',
    iata_faa: 'YBC',
    icao: 'CYBC',
    lat: 49.1325,
    lng: -68.204444,
    alt: 71,
    tz: 'America/Toronto',
  },
  {
    name: 'Bagotville',
    city: 'Bagotville, Canada',
    iata_faa: 'YBG',
    icao: 'CYBG',
    lat: 48.330555,
    lng: -70.996391,
    alt: 522,
    tz: 'America/Toronto',
  },
  {
    name: 'Baker Lake',
    city: 'Baker Lake, Canada',
    iata_faa: 'YBK',
    icao: 'CYBK',
    lat: 64.298889,
    lng: -96.077778,
    alt: 59,
    tz: 'America/Winnipeg',
  },
  {
    name: 'Campbell River',
    city: 'Campbell River, Canada',
    iata_faa: 'YBL',
    icao: 'CYBL',
    lat: 49.950832,
    lng: -125.270833,
    alt: 346,
    tz: 'America/Vancouver',
  },
  {
    name: 'Brandon Muni',
    city: 'Brandon, Canada',
    iata_faa: 'YBR',
    icao: 'CYBR',
    lat: 49.91,
    lng: -99.951944,
    alt: 1343,
    tz: 'America/Winnipeg',
  },
  {
    name: 'Cambridge Bay',
    city: 'Cambridge Bay, Canada',
    iata_faa: 'YCB',
    icao: 'CYCB',
    lat: 69.108055,
    lng: -105.138333,
    alt: 90,
    tz: 'America/Edmonton',
  },
  {
    name: 'Nanaimo',
    city: 'Nanaimo, Canada',
    iata_faa: 'YCD',
    icao: 'CYCD',
    lat: 49.052333,
    lng: -123.870167,
    alt: 93,
    tz: 'America/Vancouver',
  },
  {
    name: 'Castlegar',
    city: 'Castlegar, Canada',
    iata_faa: 'YCG',
    icao: 'CYCG',
    lat: 49.296389,
    lng: -117.6325,
    alt: 1624,
    tz: 'America/Vancouver',
  },
  {
    name: 'Miramichi',
    city: 'Chatham, Canada',
    iata_faa: 'YCH',
    icao: 'CYCH',
    lat: 47.007778,
    lng: -65.449167,
    alt: 108,
    tz: 'America/Halifax',
  },
  {
    name: 'Charlo',
    city: 'Charlo, Canada',
    iata_faa: 'YCL',
    icao: 'CYCL',
    lat: 47.990833,
    lng: -66.330278,
    alt: 132,
    tz: 'America/Halifax',
  },
  {
    name: 'Kugluktuk',
    city: 'Coppermine, Canada',
    iata_faa: 'YCO',
    icao: 'CYCO',
    lat: 67.816667,
    lng: -115.143889,
    alt: 74,
    tz: 'America/Edmonton',
  },
  {
    name: 'Coronation',
    city: 'Coronation, Canada',
    iata_faa: 'YCT',
    icao: 'CYCT',
    lat: 52.075001,
    lng: -111.445278,
    alt: 2595,
    tz: 'America/Edmonton',
  },
  {
    name: 'Chilliwack',
    city: 'Chilliwack, Canada',
    iata_faa: 'YCW',
    icao: 'CYCW',
    lat: 49.152779,
    lng: -121.93889,
    alt: 32,
    tz: 'America/Vancouver',
  },
  {
    name: 'Clyde River',
    city: 'Clyde River, Canada',
    iata_faa: 'YCY',
    icao: 'CYCY',
    lat: 70.486111,
    lng: -68.516667,
    alt: 87,
    tz: 'America/Toronto',
  },
  {
    name: 'Fairmont Hot Springs',
    city: 'Coral Harbour, Canada',
    iata_faa: 'YZS',
    icao: 'CYCZ',
    lat: 64.193333,
    lng: -83.359444,
    alt: 2661,
    tz: 'America/Coral_Harbour',
  },
  {
    name: 'Dawson City',
    city: 'Dawson, Canada',
    iata_faa: 'YDA',
    icao: 'CYDA',
    lat: 64.043056,
    lng: -139.127778,
    alt: 1215,
    tz: 'America/Vancouver',
  },
  {
    name: 'Burwash',
    city: 'Burwash, Canada',
    iata_faa: 'YDB',
    icao: 'CYDB',
    lat: 61.371111,
    lng: -139.040556,
    alt: 2647,
    tz: 'America/Vancouver',
  },
  {
    name: 'Princeton',
    city: 'Princeton, Canada',
    iata_faa: 'YDC',
    icao: 'CYDC',
    lat: 49.468056,
    lng: -120.511389,
    alt: 2298,
    tz: 'America/Vancouver',
  },
  {
    name: 'Deer Lake',
    city: 'Deer Lake, Canada',
    iata_faa: 'YDF',
    icao: 'CYDF',
    lat: 49.210833,
    lng: -57.391388,
    alt: 72,
    tz: 'America/St_Johns',
  },
  {
    name: 'Dease Lake',
    city: 'Dease Lake, Canada',
    iata_faa: 'YDL',
    icao: 'CYDL',
    lat: 58.422222,
    lng: -130.032222,
    alt: 2600,
    tz: 'America/Vancouver',
  },
  {
    name: 'Dauphin Barker',
    city: 'Dauphin, Canada',
    iata_faa: 'YDN',
    icao: 'CYDN',
    lat: 51.100834,
    lng: -100.0525,
    alt: 999,
    tz: 'America/Winnipeg',
  },
  {
    name: 'Dawson Creek',
    city: 'Dawson Creek, Canada',
    iata_faa: 'YDQ',
    icao: 'CYDQ',
    lat: 55.742333,
    lng: -120.183,
    alt: 2148,
    tz: 'America/Dawson_Creek',
  },
  {
    name: 'Edmonton Intl',
    city: 'Edmonton, Canada',
    iata_faa: 'YEG',
    icao: 'CYEG',
    lat: 53.309723,
    lng: -113.579722,
    alt: 2373,
    tz: 'America/Edmonton',
  },
  {
    name: 'Arviat',
    city: 'Eskimo Point, Canada',
    iata_faa: 'YEK',
    icao: 'CYEK',
    lat: 61.094166,
    lng: -94.070833,
    alt: 32,
    tz: 'America/Winnipeg',
  },
  {
    name: 'Estevan',
    city: 'Estevan, Canada',
    iata_faa: 'YEN',
    icao: 'CYEN',
    lat: 49.210278,
    lng: -102.965833,
    alt: 1905,
    tz: 'America/Regina',
  },
  {
    name: 'Edson',
    city: 'Edson, Canada',
    iata_faa: 'YET',
    icao: 'CYET',
    lat: 53.578888,
    lng: -116.465,
    alt: 3041,
    tz: 'America/Edmonton',
  },
  {
    name: 'Eureka',
    city: 'Eureka, Canada',
    iata_faa: 'YEU',
    icao: 'CYEU',
    lat: 79.994722,
    lng: -85.814167,
    alt: 256,
    tz: 'America/Winnipeg',
  },
  {
    name: 'Inuvik Mike Zubko',
    city: 'Inuvik, Canada',
    iata_faa: 'YEV',
    icao: 'CYEV',
    lat: 68.304167,
    lng: -133.482778,
    alt: 224,
    tz: 'America/Edmonton',
  },
  {
    name: 'Iqaluit',
    city: 'Iqaluit, Canada',
    iata_faa: 'YFB',
    icao: 'CYFB',
    lat: 63.75639,
    lng: -68.555832,
    alt: 110,
    tz: 'America/Toronto',
  },
  {
    name: 'Fredericton',
    city: 'Fredericton, Canada',
    iata_faa: 'YFC',
    icao: 'CYFC',
    lat: 45.868889,
    lng: -66.537222,
    alt: 68,
    tz: 'America/Halifax',
  },
  {
    name: 'Forestville',
    city: 'Forestville, Canada',
    icao: 'CYFE',
    lat: 48.746111,
    lng: -69.097222,
    alt: 293,
    tz: 'America/Toronto',
  },
  {
    name: 'Flin Flon',
    city: 'Flin Flon, Canada',
    iata_faa: 'YFO',
    icao: 'CYFO',
    lat: 54.678055,
    lng: -101.681667,
    alt: 997,
    tz: 'America/Winnipeg',
  },
  {
    name: 'Fort Resolution',
    city: 'Fort Resolution, Canada',
    iata_faa: 'YFR',
    icao: 'CYFR',
    lat: 61.180832,
    lng: -113.689722,
    alt: 526,
    tz: 'America/Edmonton',
  },
  {
    name: 'Fort Simpson',
    city: 'Fort Simpson, Canada',
    iata_faa: 'YFS',
    icao: 'CYFS',
    lat: 61.760153,
    lng: -121.236525,
    alt: 555,
    tz: 'America/Edmonton',
  },
  {
    name: 'Kingston',
    city: 'Kingston, Canada',
    iata_faa: 'YGK',
    icao: 'CYGK',
    lat: 44.225277,
    lng: -76.596944,
    alt: 305,
    tz: 'America/Toronto',
  },
  {
    name: 'La Grande Riviere',
    city: 'La Grande Riviere, Canada',
    iata_faa: 'YGL',
    icao: 'CYGL',
    lat: 53.625278,
    lng: -77.704167,
    alt: 639,
    tz: 'America/Toronto',
  },
  {
    name: 'Gaspe',
    city: 'Gaspe, Canada',
    iata_faa: 'YGP',
    icao: 'CYGP',
    lat: 48.775278,
    lng: -64.478611,
    alt: 108,
    tz: 'America/Toronto',
  },
  {
    name: 'Geraldton Greenstone Regional',
    city: 'Geraldton, Canada',
    iata_faa: 'YGQ',
    icao: 'CYGQ',
    lat: 49.778332,
    lng: -86.939445,
    alt: 1144,
    tz: 'America/Toronto',
  },
]